### PR TITLE
Fix SCSS lists

### LINKED ISSUE #28: Output format of arrays in Sass maps
`getStyleSafeValue` doesn't produce the expected output for arrays when output to the value of a key in a Sass `map`

Consider this source data:

```json
// with options.name = 'grids' & options.useSassMaps = true
{
    "base": {
        "gutter": 15,
        "columns": 12,
        "output": [ 2, 10, 12 ]
    }
};
```

This currently results in the Sass output:

```scss
$grids: (
	base: (
		gutter: 15,
		columns: 12,
		output: 2,10,12
	)
);

```

This will cause a parse error in Sass, as `,` is used both as a `list` separator, and to denote the end of a `map` key's value.

The expected output would wrap list/array output in parens to avoid this ambiguity:

```scss
$grids: (
	base: (
		gutter: 15,
		columns: 12,
		output: (2,10,12)
	)
);

```

Happy to take a crack at this one if a PR would be considered, but #25 suggests you're looking refactoring `getStyleSafeValue` anyway, so thought I'd open an issue first.

### PR DESCRIPTION
**Pull request by jGleitz**
This PR fixes #28: Lists are represented incorrectly in SCSS output.

I have seen the discussion in #25 about code style and how to refactor the code before implementing this. Nevertheless, I need this feature and implemented it. This PR may serve as an intermediate bug fix until the refactor actually takes place.

This Pull Request adds simple tests for lists for every data format. Please note that I could not figure out (and did not try too hard) if and how lists work in stylus and less. I therefore adopted the "CSS style" for them.

Note: I used js beautfiy on the code to make writing in the code style easier for me. This PR therefore includes some whitespace changes. But these actually enforce consistency in the code, so they should not be "bad".

### CODE REVIEW

**Comment by jGleitz** [comment]
I just realised a big flaw of my approach: It cannot handle objects in arrays. 

But at this point, it's totally unclear how to handle such a situation: Objects in Arrays make totally sense in YAML, JSON, SASS, etc., but have no valid representation in CSS. How should `grunt-shared-config` handle this?

**Comment by MathiasPaumgarten** [comment]
Hi,
thank you for this contribution and first off, I actually really appreciate the correction in white space.

I'm not sure what you mean. It can't compile all the way to CSS since CSS supports no kind of variables. But like you said, YAML, JSON, JS, SASS allow nested lists, right? So that should work.

**Comment by jGleitz** [comment]
> It can't compile all the way to CSS since CSS supports no kind of variables.

That's the point. What if the user still tries to export nested objects to CSS? We could:

* fail
* leave them out and
  * print a warning
  * stay silent about it

**Comment by MathiasPaumgarten** [comment]
> What if the user still tries to export nested objects to CSS?

But my point is that `grunt-shared-config` never transpiles to CSS, because CSS is silly and doesn't support anything useful :smile: (Sorry for the unnecessary rant)

I'm I totally misunderstanding you?

**Comment by jGleitz** [comment]
> `grunt-shared-config` never transpiles to CSS

Ouups… true. Sorry for the confusion!

Are there maps in less and stylus? Looking it up in google didn't get me too much about that.

**Comment by jGleitz** [comment]
From my point of view, this PR is now ready to merge. 

I solved nested objects like this:

 *  `SASS, SCSS, JSON, JS (all variations)` get converted as expected
 * `STYLUS, LESS` 
    * lists nested in lists get flattened
    * objects in lists become `null`

**Comment by MathiasPaumgarten** [comment]
That sounds awesome. I wasn't aware if there was a nested list version in __Stylus__ or __Less__. I wasn't the one implementing that even. That was thanks to PR by @ceee.

**Comment by MathiasPaumgarten** [comment]
Thanks so much for supporting this project.

**Pull request merged**
